# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c2f7f600c34069dfacd086cc956e3f0f05629232e17004510f74f9a51f066c33a159d04f3f46be3f690d6d4b0b26aed7cbb5c9bd5d51ab95487180499b321fb

test:
  secret_key_base: 2a951719ec734b24de386f8798e1551ad88f9615f00587f15dd5a26b5768d3a7c7c017c0a1d9e60d5af7d08e4af46b78a2d8916e4598000d9559699086c05584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
